call pathogen#infect()
call pathogen#helptags()

let mapleader=','
syntax on

set mouse=a
set ruler
set number
set showmode
set showcmd
set showmatch

set hlsearch
set ignorecase
set smartcase
set incsearch

set autowrite
set hidden

set ai
set sw=4
set ts=4
set t_Co=256
set laststatus=2
set expandtab
set fencs=utf-8,cp936
set backspace=indent,eol,start

if has("autocmd")
  au BufReadPost * if line("'\"")>1 && line("'\"")<=line("$") | exe "normal! g'\"" | endif
endif

imap <c-c>    <ESC>
imap <s-tab>  <c-p>
imap <c-w>n   :tabnew<CR>
map  <c-w>n   :tabnew<CR>
map  <leader>1 :tabn 1<CR>
map  <leader>2 :tabn 2<CR>
map  <leader>3 :tabn 3<CR>
map  <leader>4 :tabn 4<CR>
map  <leader>e :NERDTreeTabsToggle<CR>
imap <leader>e <ESC>:NERDTreeTabsToggle<CR>
map  <leader>t :TagbarToggle<CR>
imap <leader>t <ESC>:TagbarToggle<CR>

au BufNewFile,BufReadPost *.coffee setl sw=2 expandtab
let NERDTreeIgnore=['\.vim$','\~$','\.pyc$', '\.swp$']
let NERDTreeSortOrder=['^__\.py','\/$','*','\.swp$','\~$']
let NERDTreeShowBookmarks=1
let g:neocomplcache_enable_at_startup=1
let g:neocomplcache_enable_smart_case=1
let g:neocomplcache_min_syntax_length=2
let g:syntastic_check_on_open=1
let g:syntastic_echo_current_error=1
let g:syntastic_enable_highlighting=0
let g:syntastic_echo_enable_signs=1
let g:syntastic_error_symbol='x'
let g:syntastic_warning_symbol='w'
let g:syntastic_enable_balloons=1
let g:ctrlp_use_caching=1
let g:ctrlp_working_path_mode=0
let g:Powerline_symbols='fancy'
let g:pymode_doc=1
let g:pymode_doc_key='K'
let g:pymode_lint_checker="pyflakes,pep8,mccabe"
let g:pymode_lint_cwindow=1
let g:pymode_lint_message=1
let g:pymode_lint_jump=0
let g:pymode_lint_signs=1
let g:pymode_lint_mccabe_complexity=8
let g:pymode_lint_minheight=3
let g:pymode_lint_maxheight=6
let g:pymode_rope=1
let g:pymode_rope_auto_project=1
let g:pymode_rope_enable_autoimport=1
let g:pymode_rope_autoimport_generate=1
let g:pymode_rope_autoimport_underlineds=0
let g:pymode_rope_codeassist_maxfixes=10
let g:pymode_rope_sorted_completions=1
let g:pymode_rope_extended_complete=1
let g:pymode_rope_autoimport_modules=["os","sys","shutil","datetime"]
let g:pymode_rope_confirm_saving=1
let g:pymode_rope_global_prefix="<C-x>p"
let g:pymode_rope_local_prefix="<C-c>r"
let g:pymode_rope_vim_completion=1
let g:pymode_rope_guess_project=1
let g:pymode_rope_goto_def_newwin=""
let g:pymode_rope_always_show_complete_menu=0
let g:pymode_folding=0
let g:pymode_virtualenv=1
let g:pymode_utils_whitespaces=1
let g:pymode_indent=1
let g:pymode_options=1
let g:pymode_syntax=1
let g:pymode_syntax_all=1
let g:pymode_syntax_indent_errors=g:pymode_syntax_all
let g:pymode_syntax_space_errors=g:pymode_syntax_all
let g:pymode_syntax_string_formatting=g:pymode_syntax_all
let g:pymode_syntax_string_templates=g:pymode_syntax_all
let g:pymode_syntax_doctests=g:pymode_syntax_all
let g:pymode_syntax_builtin_objs=g:pymode_syntax_all
let g:pymode_syntax_builtin_funcs=g:pymode_syntax_all
let g:pymode_syntax_highlight_exceptions=g:pymode_syntax_all
let g:pymode_syntax_slow_sync=0

filetype plugin on

autocmd FileType python,perl,markdown set sw=4 ts=4 expandtab
autocmd FileType javascript,html,css set sw=2 ts=2 expandtab
autocmd FileType jade,smarty set sw=2 ts=2 expandtab

filetype on

"set background=dark
"colorscheme molokai
"colorscheme koehler
colorscheme molokai-transparent
